### ISSUE TITLE
Create cores at startup

### ISSUE THREAD

**Issue by wgudu** [docker-solr/docker-solr-examples#6]
Hello everyone !
I have 2 customized configsets.
I want to use them in a dev and prod environment.
In dev with docker-compose.
In prod with kubernetes.

The challenge is to prepare an image that, when executing the container, creates the 2 cores using your settings.
Besides that, this Solr standalone instance has security access control and i'm getting this error - 
"ERROR: Solr requires authentication for http://localhost:8983/solr/admin/info/system. Please supply valid credentials. HTTP code=401" - when executing create core scripts... 

I tried some combinations of the examples, but I was not successful.

Any tips?
Thanks !

Gudu

**Comment by makuk66** [comment]
Please limit issues here to problems with the actual examples themselves.
The solr user list is a better place for asking generic question.

There are three parts to your question:
- how to prepare the configets. See https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset
- how to pass them to the containers. If you use volume mounting, that will differ some between docker-compose and your kubernetes setup, but should be possible in both. If you use a custom docker image that includes your configsets, that's perhaps somewhat simpler.
- how to create 2 cores. See https://github.com/docker-solr/docker-solr/issues/188

**Comment by wgudu** [comment]
OK.
This question has been solved. 
If anyone needs, I can post the solution. 
Thanks.
